name: updater
description: A flutter package to check for custom app update.
version: 0.0.2+1
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  http: ^0.13.3
  open_file: ^3.2.1
  package_info_plus: ^1.0.6
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin