name: updater
description: A package to check for the custom in-app updates for Flutter.
version: 0.2.3
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.2.1+1
  http: ^1.1.0
  open_filex: ^4.3.2
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin
      ios:
        pluginClass: UpdaterPlugin
  
