name: updater
description: A package to check for the custom in-app updates for Flutter.
version: 0.2.1
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  # dio: ^5.0.3
  dio: ^5.1.2
  http: ^0.13.6
  open_filex: ^4.3.2
  # package_info_plus: ^3.0.3
  package_info_plus: ^3.1.2
  path_provider: ^2.0.15
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  # mockito: ^5.3.2
  mockito: ^5.4.0
  build_runner: ^2.4.4

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin
      ios:
        pluginClass: UpdaterPlugin
  
