name: updater
description: A package to check for the custom in-app updates for Flutter.
version: 0.0.8
homepage: https://github.com/MarsadMaqsood/updater

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  http: ^0.13.4
  open_file: ^3.2.1
  package_info_plus: ^1.4.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.marsad.updater
        pluginClass: UpdaterPlugin
  